routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
  Route::get('/', function (){
      return view('index');
  });

  Route::get('/notebooks/notes', function(){
    return view('notes.index');
  });

  Route::resource('/notebooks', 'NotebooksController');

  Route::resource('/notes', 'NotesController', ['except' => [
    'index', 'create'
  ]]);

  Route::get('/notebooks/{id}/notes', 'NotesController@index')->name('notes.index');

  Route::get('/notes/{notebookId}/create', 'NotesController@create')->name('notes.create');

  Route::resource('/admin', 'AdminController');

  Route::resource('/roles', 'RoleController');
  //Route::get('notes/{notebookId}/createNote', 'NotesController@createNote')->name('notes.createNote');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.main')

@section('title', 'Home')
@php
  $currentpage = 'index'
@endphp
@section('content')
  <!-- Main component for call to action -->
  <div class="container">
    <div class="row">
      <h1>Notebook</h1>
      <p>Store and organise your thoughts in notebook and NoteBook web app makes this easier than ever</p>
      <p>
          <a class="waves-effect waves-light btn-large blue darken-2" href="{{ route('notebooks.index') }}"><i class="material-icons right">book</i>Your NoteBooks</a>
      </p>
    </div>
  </div>  <!-- /container -->
@endsection