routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
  Route::get('/', function (){
      return view('index');
  });

  Route::get('/notebooks/notes', function(){
    return view('notes.index');
  });

  Route::resource('/notebooks', 'NotebooksController');

  Route::resource('/notes', 'NotesController', ['except' => [
    'index', 'create'
  ]]);

  Route::get('/notebooks/{id}/notes', 'NotesController@index')->name('notes.index');

  Route::get('/notes/{notebookId}/create', 'NotesController@create')->name('notes.create');

  Route::resource('/admin', 'AdminController');

  Route::resource('/roles', 'RoleController');
  //Route::get('notes/{notebookId}/createNote', 'NotesController@createNote')->name('notes.createNote');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    //
    protected $fillable = ['title', 'body', 'notebook_id'];

    /**
     * Get the notebook that owns the model.
     */
    public function notebook()
    {
        return $this->belongsTo('App\Notebook');
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Notebook;
use App\Note;
use Illuminate\Http\Request;

class NotesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        //
        $notebook = Notebook::findOrFail($id);

        $notes = $notebook->notes;

        //return $notes;
        return view('notes.index', compact('notes', 'notebook'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($notebookId)
    {
        //
      return view('notes.create')->with('id', $notebookId);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
          'title' => 'required',
          'body' => 'required',
        ]);

        Note::create($request->all());

        return redirect()->route('notes.index', $request->notebook_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $note = Note::findOrFail($id);

        return view('notes.show')->with('note', $note);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $note = Note::findOrFail($id);

        return view('notes.edit')->with('note', $note);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
          'title' => 'required',
          'body' => 'required',
        ]);

        $note = Note::findOrFail($id);
        $note->update($request->all());

        return redirect()->route('notes.index', $request->notebook_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        //
        Note::findOrFail($id)->delete();

        return redirect()->route('notes.index', $request->notebook_id);
    }
}

resources/views/notes/create.blade.php
@extends('layouts.main')

@section('title', 'Create Notes')

@php
  $currentpage = 'notes';
@endphp

@section('content')
  <div class="container">
    <div class="row">
      <h2>Create Note</h2>
    </div>

      <div class="row">
        <form class="col s12" action="{{ route('notes.store') }}" method="POST">
          {{ csrf_field() }}
          <div class="row">
            <div class="input-field col s12">
              <input id="title" type="text" class="validate" name="title">
              <label for="title">Note Title:</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <textarea id="body" name="body" class="materialize-textarea"></textarea>
              <label for="body">Description</label>
            </div>
          </div>
          <input type="hidden" name="notebook_id" value="{{ $id }}">
          <div class="center-align">
          <button class="btn waves-effect waves-light blue darken-2" type="submit" name="submit">Create Note</button>
        </div>
        </form>
      </div>

      @if ($errors->any())
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="card-panel red lighten-1">
                <ul>
                  @foreach ($errors->all() as $error)
                    <li class="black-text">{{ $error }}</li>
                  @endforeach
                </ul>
              </div>
            </div>
          </div>
      @endif
  </div>
@endsection

resources/views/notes/edit.blade.php
@extends('layouts.main')

@section('title', 'Create Notes')

@php
  $currentpage = 'notes';
@endphp

@section('content')
  <div class="container">
    <div class="row">
      <h2>Edit Note</h2>
    </div>

  <div class="row">
    <form class="col s12" action="{{ route('notes.update', $note->id) }}" method="POST">
      {{ csrf_field() }}
      {{ method_field('PUT') }}
      <div class="row">
        <div class="input-field col s12">
          <input id="title" type="text" class="validate" name="title" value="{{ $note->title }}">
          <label for="title">Note Title:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="body" name="body" class="materialize-textarea">{{ $note->body }}</textarea>
          <label for="body">Description</label>
        </div>
      </div>
      <input type="hidden" name="notebook_id" value="{{ $note->notebook_id }}">
      <div class="center-align">
      <button class="btn waves-effect waves-light blue darken-2" type="submit" name="submit">Update Note</button>
    </div>
    </form>
  </div>
  </div>

  @if ($errors->any())
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-1">
            <ul>
              @foreach ($errors->all() as $error)
                <li class="black-text">{{ $error }}</li>
              @endforeach
            </ul>
          </div>
        </div>
      </div>
  @endif
@endsection

resources/views/notes/index.blade.php
@extends('layouts.main')

@section('title', 'Notes')

@php
  $currentpage = 'notes';
@endphp

@section('content')
  <!-- Main component for call to action -->
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m12 l12">
          <h2 class>{{ title_case($notebook['name']) }}</h2>
        </div>
      </div>
    </div>
    @if (count($notes) > 0)
      @foreach ($notes as $note)
        <div class="row">
          <div class="col s12 m12 l12">
            <div class="card">
              <div class="card-content black-text">
                <span class="card-title">{{ title_case($note->title) }}</span>
                <p>{{ ucfirst($note->body) }}</p>
              </div>
              <div class="card-action">
                <div class="row center">
                  <div class="col s4 m4 l4">
                    <a class="waves-effect waves-light btn blue darken-2" href="{{ route('notes.show', $note->id) }}">View Note</a>
                  </div>
                  <div class="col s4 m4 l4">
                    <a class="waves-effect waves-light btn blue darken-2" href="{{ route('notes.edit', $note->id) }}">Edit Note</a>
                  </div>
                  <div class="col s4 m4 l4">
                    <form action="{{ route('notes.destroy', $note->id) }}" class="pull-s6" method="POST">
                      {{ csrf_field() }}
                      {{ method_field('DELETE') }}
                        <input type="hidden" name="notebook_id" value="{{ $note->notebook_id }}">

                        <button class="waves-effect waves-light btn red darken-2 round" type="submit" name="submit" onclick="Materialize.toast('Note Deleted successfully', 4000)">
                          Delete
                        </button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      @endforeach
        <div class="fixed-action-btn">
          <a class="waves-effect waves-light btn-floating btn-large blue darken-2 tooltipped" href="{{ route('notes.create', $note->notebook_id) }}" data-position="left" data-delay="50" data-tooltip="Create Note">
            <i class="large material-icons">add</i>
          </a>
        </div>
  @else
    <h3>no notes found</h3>
    <div class="fixed-action-btn">
      <a class="waves-effect waves-light btn-floating btn-large blue darken-2 tooltipped" href="{{ route('notes.create', $notebook->id) }}" data-position="left" data-delay="50" data-tooltip="Create Note">
        <i class="large material-icons">add</i>
      </a>
    </div>
  @endif

  </div> <!-- /container -->
@endsection

resources/views/notes/show.blade.php
@extends('layouts.main')

@section('title', 'Notebooks')
@php
  $currentpage = 'notes';
@endphp
@section('content')
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m12 l12">
          <h2>{{ title_case($note->title) }}</h2>
          <p>{{ ucfirst($note->body) }}</p>
        </div>
      </div>
    </div>

    <div class="row">
      <p></p>
    </div>
    </div><!-- end content -->
  </div>
@endsection