routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
  Route::get('/', function (){
      return view('index');
  });

  Route::get('/notebooks/notes', function(){
    return view('notes.index');
  });

  Route::resource('/notebooks', 'NotebooksController');

  Route::resource('/notes', 'NotesController', ['except' => [
    'index', 'create'
  ]]);

  Route::get('/notebooks/{id}/notes', 'NotesController@index')->name('notes.index');

  Route::get('/notes/{notebookId}/create', 'NotesController@create')->name('notes.create');

  Route::resource('/admin', 'AdminController');

  Route::resource('/roles', 'RoleController');
  //Route::get('notes/{notebookId}/createNote', 'NotesController@createNote')->name('notes.createNote');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Notebook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notebook extends Model
{
    //
    protected $fillable = ['name'];

    /**
     * Get the notes for the model.
     */
    public function notes()
    {
        return $this->hasMany('App\Note');
    }
}

app/Http/Controllers/NotebooksController.php
<?php

namespace App\Http\Controllers;

use App\Notebook;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NotebooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $user = Auth::user();
        $notebooks = $user->notebooks;
        return view('notebooks.index', compact('notebooks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('notebooks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
      $input =  $request->all();

      $user = Auth::user();
      $user->notebooks()->create($input);
      //Notebook::create($input);

      return redirect()->route('notebooks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $notebook = Notebook::findOrFail($id);

        $notes = $notebook->notes();

        return view('notes.index', compact('notes', 'notebook'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = Auth::user();
        $notebook = $user->notebooks()->findOrFail($id);
        //$notebook = Notebook::findOrFail($id);

        return view('notebooks.edit', compact('notebook'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        //$notebook = Notebook::findOrFail($id);
        $user = Auth::user();
        $notebook = $user->notebooks()->findOrFail($id);
        $notebook->update($request->all());

        return redirect()->route('notebooks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = Auth::user();
        $user->notebooks()->findOrFail($id)->delete();
        //Notebook::findOrFail($id)->delete();

        return redirect()->route('notebooks.index');
    }
}

resources/views/notebooks/create.blade.php
@extends('layouts.main')

@section('title', 'Create Notebook')
@php
  $currentpage = 'notebookAction';
@endphp
@section('content')
  <div class="container">
    <div class="row">
      <h2>Create Notebook</h2>
    </div>

  <div class="row">
    <form class="col s12" action="{{ route('notebooks.store') }}" method="POST">
      {{ csrf_field() }}
      <div class="row">
        <div class="input-field col s12">
          <input id="name" type="text" class="validate" name="name">
          <label for="name">Notebook Name:</label>
        </div>
      </div>
      <div class="center-align">
      <button class="btn waves-effect waves-light blue darken-2" type="submit" name="submit">Create Notebook</button>
    </div>
    </form>
  </div>
  </div>
@endsection

resources/views/notebooks/edit.blade.php
@extends('layouts.main')

@section('title', 'Create Notebook')
@php
  $currentpage = 'notebookAction';
@endphp
@section('content')
  <div class="container">
    <div class="row">
      <h2>Update Notebook</h2>
    </div>

    <div class="row">
      <form class="col s12" action="{{ route('notebooks.update', $notebook->id) }}" method="POST">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="row">
          <div class="input-field col s12">
            <input id="name" type="text" class="validate" name="name" value="{{ $notebook->name }}">
            <label for="name">Notebook Name:</label>
          </div>
        </div>
        <div class="center-align">
          <button class="btn waves-effect waves-light blue darken-2" type="submit" name="submit">Update Notebook</button>
        </div>
      </form>
    </div>
  </div>
@endsection

resources/views/notebooks/index.blade.php
@extends('layouts.main')

@section('title', 'Notebooks')
@php
  $currentpage = 'notebook';
@endphp
@section('content')
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m12 l12">
          <h2 class>Your Notebooks</h2>
        </div>
      </div>
    </div>

    <!-- Notebook content -->
    <div class="row">
      @if ($notebooks == true)
        @foreach ($notebooks as $notebook)
          <div class="col s12 m4 l4">
            <div class="card">
            <div class="card-image">
              <img src="img/notebook.jpg">
              <span class="card-title">{{ title_case($notebook->name) }}</span>
              <a class="btn-floating halfway-fab waves-effect waves-light blue darken-2 btn-large" href="{{ route('notebooks.edit', $notebook->id) }}"><i class="material-icons">create</i></a>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <div class="row">
                <div class="col m6 l6">
                  <a class="waves-effect waves-light btn blue darken-2" href="{{ route('notes.index', $notebook->id) }}">View Notes</a>
                </div>
                <div class="col m6 l6">
                  <form action="{{ route('notebooks.destroy', $notebook->id) }}" class="pull-s6" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="waves-effect waves-light btn red darken-2 round" type="submit" name="submit" onclick="Materialize.toast('Notebook Deleted successfully', 4000)">
                      Delete
                    </button>
                  </form>
                </div>
              </div>


            </div>
          </div>
          </div>
        @endforeach
      @endif
    </div><!-- end content -->
  </div>
  <div class="fixed-action-btn">
    <a class="waves-effect waves-light btn-floating btn-large blue darken-2 tooltipped" href="{{ route('notebooks.create') }}" data-position="left" data-delay="50" data-tooltip="Create Notebook">
      <i class="large material-icons">add</i>
    </a>
  </div>
@endsection