routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
  Route::get('/', function (){
      return view('index');
  });

  Route::get('/notebooks/notes', function(){
    return view('notes.index');
  });

  Route::resource('/notebooks', 'NotebooksController');

  Route::resource('/notes', 'NotesController', ['except' => [
    'index', 'create'
  ]]);

  Route::get('/notebooks/{id}/notes', 'NotesController@index')->name('notes.index');

  Route::get('/notes/{notebookId}/create', 'NotesController@create')->name('notes.create');

  Route::resource('/admin', 'AdminController');

  Route::resource('/roles', 'RoleController');
  //Route::get('notes/{notebookId}/createNote', 'NotesController@createNote')->name('notes.createNote');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/includes/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="{{route('admin.index')}}">Admin</a></h1>
                </div>
            </div>

            <div class="col-md-2 pull-right">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{Auth::user()->name}} <b
                                            class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <li><a href="{{url('/')}}">Front End</a></li>
                                    {{--<li><a href="{{url('/logout')}}">Logout</a></li>--}}
                                    <div>
                                        <a class="dropdown-item" href="{{ url('/logout') }}" onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>
                                        <form action="{{ url('/logout') }}" id="logout-form" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/admin/includes/sidenav.blade.php
{{-- Side Navigation --}}
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block;">
        <ul class="nav">
            <!-- Main menu -->
            <li class="current"><a href="#"><i class="glyphicon glyphicon-home"></i>
                    Dashboard</a></li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Role
                    <span class="caret pull-right"></span>
                </a>
                <!-- Sub menu -->
                <ul>
                    <li class="sub-menu"><a href="#"><i class="glyphicon glyphicon-home"></i>
                            Users</a></li>
                </ul>
                <!-- Sub menu -->
                <ul>
                    <li class="sub-menu"><a href="{{ route('roles.index') }}"><i class="glyphicon glyphicon-home"></i>
                            Roles</a></li>
                </ul>
            </li>

        </ul>
    </div>
</div> <!-- ADMIN SIDE NAV-->